apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev-heal.infoviz.co
    http:
      paths:
      - path: /microservice1
        pathType: Prefix
        backend:
          service:
            name: microservice1
            port:
              number: 80
      - path: /microservice2
        pathType: Prefix
        backend:
          service:
            name: microservice2
            port:
              number: 80